### ISSUE TITLE
Module branch

### ISSUE THREAD

**Issue by engcang** [url-kaist/Quatro#8]
Hi.

I made a  trimmed code branch to be used as a module in other packages as [here](https://github.com/engcang/Quatro).
If you can create a new separate branch for it, I'd love to push this branch via pull request, if you like it.
(Otherwise, I cannot open a pull request to a new branch from my end)

With the module branch, Quatro can be easily imported and used in other packages as follows:
[CMakeLists.txt](https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/CMakeLists.txt#L32)
[Header](https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/include/main.h#L39-L40)
[Method](https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/src/methods.cpp#L126)

Or, simply as explained in [here](https://github.com/engcang/Quatro#use-case)

### What are good points of module branch?
Looking into these two branches, we can see that a module branch can be used as `submodule` in github package easier as third party without any further steps of trimming codes (even those steps cannot be reflected to the original package, as the module is imported as `submodule`, again)
+ [main branch](https://github.com/hku-mars/ikd-tree) - including official explanation and examples
+ [module branch](https://github.com/hku-mars/ikd-tree/tree/fast_lio) - can be easily added and used as `submodule` in other packages

**Comment by LimHyungTae** [comment]
Yo bro, I made a module branch. Please do PR.
